# Generated by Django 4.0.6 on 2022-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
