# Generated by Django 4.0.6 on 2022-08-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_address',
            name='Order_note',
        ),
    ]
